[package]
name = "figure-tracker"
version = "0.1.0"
authors = ["DaRealFreak <steffen.keuper@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rusqlite]
version = "0.21.0"
features = ["bundled"]