[package]
name = "figure-tracker"
version = "0.1.0"
authors = ["DaRealFreak <steffen.keuper@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rusqlite]
version = "0.21.0"
features = ["bundled"]

[dependencies.clap]
git = "https://github.com/clap-rs/clap"
version = "3.0.0-beta.1"
features = ["yaml"]

[dependencies]
html5ever = "0.25.1"
hyper = "0.13.2"
