database:
  path: figure_tracker.db
general:
  # your currency code after ISO 4217 (https://en.wikipedia.org/wiki/ISO_4217)
  currency: EUR
notifications:
  telegram:
    active: false
    # you'll require a telegram bot API key which you can easily create here:
    # https://core.telegram.org/bots#3-how-do-i-create-a-bot
    api_key:
    # you'll also require your telegram user ID so we know who to send the notifications to
    user_id:
  discord:
    active: false
    # you'll require a client token for the discord bot from which you want to send notifications from
    client_token:
    # the receiving user of the notifications, make sure you can receive messages from the bot (same server/everyone setting)
    user_id:
conversion:
  # tax percentage which applies to the import (found value + shipping) * (1 + taxes), key is the currency code after ISO 4217
  taxes:
    # f.e. 0.19 for 19% taxes
    # the empty currencies are all currently found currencies in the sites we support
    JPY:
    USD:
    EUR:
    HKD:
    AUD:
    CAD:
    GBP:
  # flat value added to the value before applying taxes, key is once again the currency code after ISO 4217
  shipping:
    # f.e. 40 for 40€ averaging shipping costs
    JPY:
    USD:
    EUR:
    HKD:
    AUD:
    CAD:
    GBP:
connection:
  # option to set the user agent of the requests to the sites
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"
  # option to use a proxy for all connections in case a site is region locked or your IP got banned
  proxy:
    host:
    port: 80
    username:
    password: