name: build
on:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.lock'
  pull_request:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.lock'

jobs:
  build_and_test:
    name: Build Release
    timeout-minutes: 30
    strategy:
      matrix:
        # macos-latest is too expensive for monthly limit, don't build on it while repo is private
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features